package org.hms.medica.doctor.model;

public enum Specialty {
    GENERAL_PRACTICE, PEDIATRICS, CARDIOLOGY, NEUROLOGY, ONCOLOGY,
    ORTHOPEDICS, DERMATOLOGY, PSYCHIATRY, OBSTETRICS_GYNECOLOGY,
    OPHTHALMOLOGY, ENT, UROLOGY, NEPHROLOGY, GASTROENTEROLOGY,
    ENDOCRINOLOGY, PULMONOLOGY, RHEUMATOLOGY, EMERGENCY_MEDICINE,
    RADIOLOGY, PATHOLOGY, ANESTHESIOLOGY, SURGERY
}
